import {faAward, faBriefcase, faChalkboardTeacher, faLayerGroup, faMicrochip, faUserGraduate} from "@fortawesome/free-solid-svg-icons";

export const timelineElements = [
    {
        id: "fis-clearing-settlement",
        type: "work",
        title: "Software Engineer Senior",
        organization: "FIS",
        location: "Jacksonville, FL",
        period: "Jan 2026 - Present",
        icon: faMicrochip,
        hue: 194,
        summary: "Designing resilient clearing and settlement systems for high-volume transaction processing.",
        bullets: [
            "Fault-tolerant workflows for clearing and settlement",
            "Large transaction datasets modeled and processed with Spark",
            "Batch reliability patterns similar to Global Payments core processing",
            "Failure recovery, replay, and operational visibility for payment flows",
        ],
        tags: ["FIS", "Spark", "Settlement", "Reliability"],
    },
    {
        id: "georgia-tech-omscs",
        type: "education",
        title: "M.S. Computer Science",
        organization: "Georgia Tech",
        location: "Online",
        period: "Jan 2026 - Dec 2027",
        icon: faUserGraduate,
        hue: 48,
        summary: "Pursuing a second CS master's with a machine learning focus.",
        bullets: [
            "Semester starts Jan 2026",
            "Studying machine learning and applied AI systems",
            "Building stronger CS theory depth alongside production experience",
            "Expected graduation Dec 2027",
        ],
        tags: ["Georgia Tech", "ML", "CS"],
    },
    {
        id: "global-payments-core-batch",
        type: "work",
        title: "Software Engineer Senior",
        organization: "Global Payments",
        location: "Columbus, GA",
        period: "Jan 2022 - Jan 2026",
        icon: faLayerGroup,
        hue: 24,
        summary: "Built modern payment platforms that moved core batch processing beyond legacy mainframes.",
        bullets: [
            "Distributed payment processing services on AWS",
            "Kafka, Airflow, Spark, and Java Spring for core batch architecture",
            "Posting and financial control logic rebuilt from legacy behavior",
            "Self-healing retries, observability, and fault-tolerant job orchestration",
        ],
        tags: ["AWS", "Kafka", "Spark", "Java"],
    },
    {
        id: "aflac-apprenticeship",
        type: "work",
        title: "IT Apprenticeship",
        organization: "Aflac",
        location: "Columbus, GA",
        period: "Apr 2021 - Dec 2021",
        icon: faBriefcase,
        hue: 348,
        summary: "Built enterprise Java services and learned legacy modernization from the inside.",
        bullets: [
            "J2EE and WebSphere services for enterprise integrations",
            "Mainframe modernization patterns from COBOL-era systems",
            "Parallel API testing workflows for faster validation",
            "Early foundation in production Java and service reliability",
        ],
        tags: ["Java", "J2EE", "WebSphere"],
    },
    {
        id: "csu-stem-mentor",
        type: "teaching",
        title: "Graduate Assistant",
        organization: "Columbus State University",
        location: "Columbus, GA",
        period: "Aug 2020 - Aug 2021",
        icon: faChalkboardTeacher,
        hue: 92,
        summary: "Mentored STEM students while sharpening communication and coaching skills.",
        bullets: [
            "Course support, tutoring, and lab guidance",
            "One-on-one mentoring for STEM students",
            "Teaching through problem solving instead of memorization",
            "Clearer technical communication through repeated coaching",
        ],
        tags: ["Mentoring", "STEM", "Teaching"],
    },
    {
        id: "csu-degrees",
        type: "education",
        title: "B.S. and M.S. Computer Science",
        organization: "Columbus State University",
        location: "Columbus, GA",
        period: "Aug 2016 - Aug 2021",
        icon: faUserGraduate,
        hue: 162,
        summary: "Built the foundation for software engineering, systems, and applied CS work.",
        bullets: [
            "Software development graduate track",
            "Systems, algorithms, databases, and application design",
            "Undergraduate and graduate CS foundation",
            "Project-heavy coursework that shaped practical engineering habits",
        ],
        tags: ["CS", "Software", "Systems"],
    },
    {
        id: "ieee-southeastcon",
        type: "award",
        title: "IEEE SoutheastCon",
        organization: "Published Research",
        location: "Huntsville, AL",
        period: "Spring 2019",
        icon: faAward,
        hue: 288,
        summary: "Published NFC-based multi-factor authentication research.",
        bullets: [
            "Mobile HCE authentication with NFC",
            "AES-backed Windows login prototype",
            "pGina integration for custom authentication flow",
            "Research presented through IEEE SoutheastCon",
        ],
        tags: ["Security", "NFC", "Android", "IEEE"],
    },
];
